#if defined(LANGUAGE_EN_US)
#define TXT_SETTINGS "Settings"
#define TXT_BACK "<- Back"
#define TXT_REPOSITORY "Repository"
#define TXT_INTERSTELLAR "Interstellar"
#define TXT_IR "Infrared"
#define TXT_MUTE "Mute"
#define TXT_MUTE_TXT_UPPER "MUTE"
#define TXT_CHANNEL_UP "Channel +"
#define TXT_CHANNEL_UP_UPPER "CHANNEL +"
#define TXT_CHANNEL_DOWN "Channel -"
#define TXT_CHANNEL_DOWN_UPPER "CHANNEL -"
#define TXT_UP "Up"
#define TXT_UP_UPPER "UP"
#define TXT_DOWN "Down"
#define TXT_DOWN_UPPER "DOWN"
#define TXT_LEFT "Left"
#define TXT_LEFT_UPPER "LEFT"
#define TXT_RIGHT "Right"
#define TXT_RIGHT_UPPER "RIGHT"
#define TXT_BATTERY_INFO "Battery Info"
#define TXT_BATTERY "Battery: "
#define TXT_EXIT "Press any key to exit"
#define TXT_WIFI_BEACON_FUNNY "Beacon Funny"
#define TXT_WIFI_BEACON_FUNNY_BR "Beacon Funny (BR)"
#define TXT_BEACON_ATTACK "Beacon Attack"
#define TXT_BEACON_ATTACK_1 "BEACON"
#define TXT_BEACON_ATTACK_2 "ATTACK"
#define TXT_RND_SSID " - Random SSIDs\n"
#define TXT_BEACON_ATTACK_RND "Beacon Random"
#define TXT_WIFI_SCAN_1 "WiFi"
#define TXT_WIFI_SCAN_2 "SCAN"
#define TXT_WIFI_RESCAN "-> RESCAN"
#define TXT_WIFI_OPEN "Open"
#define TXT_WIFI_CHANNEL "Channel: "
#define TXT_WIFI_SIGNAL "Signal: "
#define TXT_WIFI_CRYPT "Crypt: "
#define TXT_SEL_BACK "\nNext: Back\n"
#define TXT_HOLD_ATTACK "Hold Ok: Attack\n"
#define TXT_WIFI_SCAN "Scan WiFi"
#define TXT_WIFI_SACANNING "SCANNING..."
#define TXT_WIFI_PORTAL "Clone Portal"
#define TXT_WIFI_DEAUTH "Deauth Attack"
#define TXT_WIFI_COMBINED "Deauth + Clone"
#define TXT_DEAUTH_STOP "ESC: Stop DEAUTH"
#define TXT_WF_CHANN "Channel:"
#define TXT_DEAUTH_START "Select>Start DEAUTH\n"
#define TXT_SA_CRASH "SourApple Crash"
#define TXT_ADV "Advertising: "
#define TXT_SP_RND "Swift Pair Random"
#define TXT_SEL_EXIT2 "ESC: Exit"
#define TXT_CMB_BT_SPAM " Combined BT Spam"
#define TXT_AD_SPAM "Android Spam"
#define TXT_AJ_TRANSF_NM "Transfer Number"
#define TXT_AJ_TV_COLOR "TV Color Balance"
#define TXT_STP_NW_PH "Setup New Phone"
#define TXT_SA_ADV "SourApple Advertisement: "
#define TXT_SP_ADV "SwiftPair Advertisement: '%s' - "
#define TXT_AD_SPAM_ADV "Android Spam Advertisement: "
#define TXT_AJ_ADV "AppleJuice Advertisement: "
#define TXT_DEFAULT_AP_SSID_NAME "Free WiFi"
#define TXT_SOUNDS "Sounds"
#define TXT_IMPERIAL_MARCH_SOUND "Imperial March"
#define TXT_SIGNAL_LEVEL "Signal Level"
#define TXT_VENDOR "Vendor: "
#define TXT_NEVER "Never"
#define TXT_SEC "seconds"
#define TXT_MIN "minutes"
#define TXT_SCREEN_SAVER_1 "SCREEN"
#define TXT_SCREEN_SAVER_2 "SAVER"
#define TXT_SCREEN_BRIGHTNESS_1 "SCREEN"
#define TXT_SCREEN_BRIGHTNESS_2 "BRIGHTNESS"
#define TXT_SET_FGCOLOR_1 "MAIN"
#define TXT_SET_FGCOLOR_2 "COLOR"
#define TXT_SET_BGCOLOR_1 "BACKGROUND"
#define TXT_SET_BGCOLOR_2 "COLOR"
#define TXT_THEME_1 "COLOR"
#define TXT_THEME_2 "THEME"
#define TXT_BLACK "Black"
#define TXT_NAVY "Navy"
#define TXT_DARKGREEN "Dark Green"
#define TXT_DARKCYAN "Dark Cyan"
#define TXT_MAROON "Maroon"
#define TXT_PURPLE "Purple"
#define TXT_OLIVE "Olive"
#define TXT_LIGHTGREY "Light Grey"
#define TXT_DARKGREY "Dark Grey"
#define TXT_BLUE "Blue"
#define TXT_GREEN "Green"
#define TXT_CYAN "Cyan"
#define TXT_RED "Red"
#define TXT_MAGENTA "Magenta"
#define TXT_YELLOW "Yellow"
#define TXT_WHITE "White"
#define TXT_ORANGE "Orange"
#define TXT_GREENYELLOW "Green Yellow"
#define TXT_PINK "Pink"
#define TXT_COLOR "Custom Colors"
#define TXT_COLOR_WORD "Color"
#define TXT_THEME_WORD "Theme"
#define TXT_BRIGHTNESS_WORD "Brightness"
#define TXT_CLEAR_SETTINGS "RESTORING SETTINGS"
#define TXT_CLEAR_SETTINGS_WORD "Restore Defaults"
#endif

#if defined(LANGUAGE_PT_BR)
#define TXT_SETTINGS "Configuracoes"
#define TXT_BACK "<- Voltar"
#define TXT_REPOSITORY "Repositorio"
#define TXT_INTERSTELLAR "Interestelar"
#define TXT_IR "Infravermelho"
#define TXT_MUTE "Mudo"
#define TXT_MUTE_TXT_UPPER "MUDO"
#define TXT_CHANNEL_UP "Canal +"
#define TXT_CHANNEL_UP_UPPER "CANAL +"
#define TXT_CHANNEL_DOWN "Canal -"
#define TXT_CHANNEL_DOWN_UPPER "CANAL -"
#define TXT_UP "Cima"
#define TXT_UP_UPPER "CIMA"
#define TXT_DOWN "Baixo"
#define TXT_DOWN_UPPER "BAIXO"
#define TXT_LEFT "Esquerda"
#define TXT_LEFT_UPPER "ESQUERDA"
#define TXT_RIGHT "Direita"
#define TXT_RIGHT_UPPER "DIREITA"
#define TXT_BATTERY_INFO "Status da Bateria"
#define TXT_BATTERY "Bateria: "
#define TXT_EXIT "Pressione qualquer tecla para sair"
#define TXT_WIFI_BEACON_FUNNY "Beacon Engracado"
#define TXT_WIFI_BEACON_FUNNY_BR "Beacon Eng. (BR)"
#define TXT_BEACON_ATTACK "Beacon Ataque"
#define TXT_BEACON_ATTACK_1 "BEACON"
#define TXT_BEACON_ATTACK_2 "ATAQUE"
#define TXT_RND_SSID " - Random SSIDs\n"
#define TXT_BEACON_ATTACK_RND "Beacon Aleatorio"
#define TXT_WIFI_SCAN_1 "ESCANEAR"
#define TXT_WIFI_SCAN_2 "WiFi"
#define TXT_WIFI_RESCAN "-> REESCANEAR"
#define TXT_WIFI_OPEN "Aberto"
#define TXT_WIFI_CHANNEL "Canal: "
#define TXT_WIFI_SIGNAL "Sinal: "
#define TXT_WIFI_CRYPT "Cripto: "
#define TXT_SEL_BACK "\nProx: Voltar\n"
#define TXT_HOLD_ATTACK "Pressione Ok: Atacar\n"
#define TXT_WIFI_SCAN "Escanear WiFi"
#define TXT_WIFI_SACANNING "ESCANEANDO..."
#define TXT_WIFI_PORTAL "Portal Clone"
#define TXT_WIFI_DEAUTH "Ataque Deauth"
#define TXT_WIFI_COMBINED "Deauth + Clone"
#define TXT_DEAUTH_STOP "ESC: Parar DEAUTH"
#define TXT_WF_CHANN "Canal:"
#define TXT_DEAUTH_START "Selecionar>Iniciar DEAUTH\n"
#define TXT_SA_CRASH "SourApple Crash"
#define TXT_ADV "Aviso: "
#define TXT_SP_RND "Swift Pair Aleatorio"
#define TXT_SEL_EXIT2 "\n\nESC: Sair"
#define TXT_CMB_BT_SPAM "BT Spam Combinado"
#define TXT_AD_SPAM "Android Spam"
#define TXT_AJ_TRANSF_NM "Transferir Numero"
#define TXT_AJ_TV_COLOR "Balanco de Cor TV"
#define TXT_STP_NW_PH "Novo Aparelho"
#define TXT_SA_ADV "Aviso SourApple: "
#define TXT_SP_ADV "Aviso SwiftPair: '%s' - "
#define TXT_AD_SPAM_ADV "Aviso Android Spam: "
#define TXT_AJ_ADV "Aviso AppleJuice: "
#define TXT_DEFAULT_AP_SSID_NAME "WiFi Livre"
#define TXT_SOUNDS "Sons"
#define TXT_IMPERIAL_MARCH_SOUND "Marcha Imperial"
#define TXT_SIGNAL_LEVEL "Nivel de Sinal"
#define TXT_VENDOR "Fabri: "
#define TXT_NEVER "Nunca"
#define TXT_SEC "segundos"
#define TXT_MIN "minutos"
#define TXT_SCREEN_SAVER_1 "DESCANSO"
#define TXT_SCREEN_SAVER_2 "DE TELA"
#define TXT_SCREEN_BRIGHTNESS_1 "BRILHO"
#define TXT_SCREEN_BRIGHTNESS_2 "DA TELA"
#define TXT_SET_FGCOLOR_1 "COR"
#define TXT_SET_FGCOLOR_2 "PRINCIPAL"
#define TXT_SET_BGCOLOR_1 "COR"
#define TXT_SET_BGCOLOR_2 "DE FUNDO"
#define TXT_THEME_1 "TEMA"
#define TXT_THEME_2 "DE COR"
#define TXT_BLACK "Preto"
#define TXT_NAVY "Azul Escuro"
#define TXT_DARKGREEN "Verde Escuro"
#define TXT_DARKCYAN "Ciano Escuro"
#define TXT_MAROON "Vermelho Escuro"
#define TXT_PURPLE "Roxo"
#define TXT_OLIVE "Castanho"
#define TXT_LIGHTGREY "Cinzo Claro"
#define TXT_DARKGREY "Cinzo Escuro"
#define TXT_BLUE "Azul"
#define TXT_GREEN "Verde"
#define TXT_CYAN "Ciano"
#define TXT_RED "Vermelho"
#define TXT_MAGENTA "Magenta"
#define TXT_YELLOW "Amarelo"
#define TXT_WHITE "Branco"
#define TXT_ORANGE "Alaranjado"
#define TXT_GREENYELLOW "Verde Amarelo"
#define TXT_PINK "Rosa"
#define TXT_COLOR "Mudar Cores"
#define TXT_COLOR_WORD "Cor"
#define TXT_THEME_WORD "Tema"
#define TXT_BRIGHTNESS_WORD "Brilho"
#define TXT_CLEAR_SETTINGS "RESTAURANDO CONFIGURACOES"
#define TXT_CLEAR_SETTINGS_WORD "Restaurar Padrao"
#endif